name: CDK deploy

on:
  push:
    branches:
      - "master"

jobs:
  deploy:
    name: deoloy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12"
      - name: setup AWS CDK
        run: npm install -g aws-cdk@1.47.1
      - name: setup dependencies
        run: npm ci
      - name: build
        run: npm run build
      - name: deploy
        run: cdk deploy --require-approval=never
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.YOUR_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.YOUR_AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "ap-northeast-1"
