name: Build Artifact

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "^1.14"
      - name: test
        run: go test ./...
      - name: build
        run: CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o bin/main main.go
      - uses: actions/upload-artifact@v2
        name: save artifact
        with:
          name: binary
          path: bin/
