name: Test Pull Reuqest

on:
  pull_request:
    branches:
      - "*"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "^1.14"
      - name: Test code
        run: go test ./...
